import type { SeedQuestion } from '../../types'

// Authored in Phase 2 (content authoring). Target 150+ across all 13 topics.
// Mix: mcq / multi / scenario; isTricky flags the gotcha questions (⚡).
export const questions: SeedQuestion[] = [
  // ─── Topic 1: Scale from Zero to Millions ─────────────────────────────
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'A single-server app is getting slow as traffic grows. What is the FIRST infrastructure change in the standard "scale to millions" progression?',
    type: 'mcq',
    options: [
      'Add a load balancer and a pool of app servers',
      'Move the database onto its own machine',
      'Shard the database by user_id',
      'Add a CDN in front of static content',
    ],
    correct: [1],
    explanation: 'The canonical progression separates the database from the app server first. Until then, the DB competes with the web server for CPU/RAM and is the shared bottleneck. Load balancers, caches, and CDNs come after that step.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'What is the main limitation of vertical scaling (scaling up)?',
    type: 'mcq',
    options: [
      'It eliminates the single point of failure',
      'It hits a hardware ceiling and cost grows super-linearly',
      'It always requires rewriting the application',
      'It cannot serve any read traffic',
    ],
    correct: [1],
    explanation: 'Vertical scaling needs no code changes and is simple, but a single machine has a hard ceiling, costs grow faster than linearly for high-end hardware, and the machine remains a single point of failure.',
    difficulty: 1,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'For horizontal cloning (X-axis scaling) behind a load balancer to work, the app servers must be…',
    type: 'mcq',
    options: [
      'Sticky-session aware',
      'Stateless',
      'Running leader election',
      'Directly connected to each other',
    ],
    correct: [1],
    explanation: 'Statelessness means any request can be served by any server. If state lives in server memory, the LB needs sticky sessions and a server restart breaks sessions.',
    difficulty: 1,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Which of the following are TRUE of stateless application services? (select all)',
    type: 'multi',
    options: [
      'Sessions are stored in a shared store such as Redis',
      'Any server can serve any request',
      'Sticky sessions are required for correctness',
      'A server restart does not log users out',
    ],
    correct: [0, 1, 3],
    explanation: 'Stateless services push session state to a shared store, so any server can handle any request and a restart is harmless. Sticky sessions are a symptom of stateful servers, not a stateless design.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'The Z-axis of the Scale Cube splits a system by…',
    type: 'mcq',
    options: [
      'Function or domain',
      'A sharding attribute such as user_id or region',
      'Making identical full copies of the data',
      'Nothing — it is identical to the X-axis',
    ],
    correct: [1],
    explanation: 'X-axis clones whole systems, Y-axis splits by function/domain, and Z-axis splits by data — each shard runs the same code but owns a slice of the data.',
    difficulty: 1,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Scenario: a team of 8 engineers ships one large deployable. A few memory-hungry features, and one bad deploy takes down everything. Someone proposes splitting into 8 microservices immediately. What is the lowest-risk first step?',
    type: 'scenario',
    options: [
      'Split into 8 microservices right away',
      'Adopt a modular monolith with enforced module boundaries and per-module data ownership',
      'Just add more servers behind a load balancer',
      'Migrate everything to serverless functions',
    ],
    correct: [1],
    explanation: 'A modular monolith delivers most of the isolation and ownership discipline of microservices without the distributed-systems tax (network calls, data ownership, versioning, observability). Split services out only when the modular monolith cannot absorb the load or team growth.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Which scaling axis most directly helps when a single user\'s data volume is enormous?',
    type: 'mcq',
    options: [
      'X-axis cloning',
      'Y-axis by domain',
      'Z-axis by user',
      'None — only vertical scaling works',
    ],
    correct: [2],
    explanation: 'Z-axis shards by an attribute such as user_id, so one user\'s large dataset lives on one shard and the total dataset is spread across many machines.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Scenario: app servers behind a load balancer hold user sessions in local memory. A rolling deploy restarts each server. What happens?',
    type: 'scenario',
    options: [
      'Users are seamlessly migrated to another server',
      'Users whose session was on a restarted server are logged out',
      'The load balancer drains the server automatically',
      'Nothing — sessions are already in the database',
    ],
    correct: [1],
    explanation: 'In-memory sessions die with the process. A rolling deploy restarts every server, so a fraction of users lose their session each wave. This is the classic argument for pushing session state to a shared store.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Which of the following problems does adding a cache in front of the database help solve? (select all)',
    type: 'multi',
    options: [
      'High read latency',
      'Database overload from repeated hot reads',
      'Concurrent write conflicts',
      'Serving reads when the database is briefly down (stale-but-present)',
    ],
    correct: [0, 1, 3],
    explanation: 'A cache shortens read latency, offloads the DB, and can keep serving stale reads during a brief DB outage. It does nothing for write conflicts — that is a consistency/transaction concern.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Traffic triples over two weeks. In the standard scaling progression, which step is typically done LAST?',
    type: 'mcq',
    options: [
      'Separate the database onto its own machine',
      'Add a CDN for static content',
      'Add a load balancer and stateless app pool',
      'Shard the database',
    ],
    correct: [3],
    explanation: 'Sharding is the last resort: it is operationally expensive and breaks joins/transactions across shards. Everything before it — DB separation, LB + stateless pool, caching, CDN, read replicas — is cheaper and should be exhausted first.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'After horizontally scaling app servers behind a load balancer, which resource usually becomes the next bottleneck?',
    type: 'mcq',
    options: [
      'The database (connections, IOPS, or disk)',
      'The CDN',
      'Client bandwidth',
      'The load balancer\'s TLS certificates',
    ],
    correct: [0],
    explanation: 'App servers are stateless and cheap to clone; the database is the shared, stateful bottleneck. This is why caching and read replicas almost always follow load balancing in the progression.',
    difficulty: 2,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'Which change eliminates the app-server single point of failure while leaving the database as a single machine?',
    type: 'mcq',
    options: [
      'Add a load balancer in front of two stateless app servers',
      'Add a read replica for the database',
      'Add a CDN',
      'Shard the database into two pieces',
    ],
    correct: [0],
    explanation: 'Two stateless app servers behind a load balancer remove the app tier\'s SPOF. The database is still a single point of failure — the next step is replication.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'scale-from-zero-to-millions',
    prompt: 'When is vertical scaling the RIGHT engineering choice?',
    type: 'mcq',
    options: [
      'For a social network targeting 100M users',
      'For workloads that are small today, where simplicity wins and the hardware ceiling is far away',
      'Never — vertical scaling is always wrong',
      'Only for the database layer',
    ],
    correct: [1],
    explanation: 'If the workload fits comfortably on one (or a few) machines, vertical scaling is simpler, cheaper to operate, and has zero distributed-systems complexity. Scale out only when the ceiling or the SPOF actually bites.',
    difficulty: 2,
    isTricky: true,
  },

  // ─── Topic 2: Back-of-the-Envelope Estimation ─────────────────────────
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Roughly how many seconds are in one day?',
    type: 'mcq',
    options: ['10⁴ (10,000)', '10⁵ (100,000)', '10⁶ (1,000,000)', '10⁷ (10,000,000)'],
    correct: [1],
    explanation: '86,400 seconds/day rounds to ~10⁵ for estimation. Memorizing these powers of ten makes QPS math trivial.',
    difficulty: 1,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: '1M DAU, each user makes 10 reads per day. What is the average read QPS (approx)?',
    type: 'mcq',
    options: ['~116 QPS', '~1,000 QPS', '~10,000 QPS', '~86,400 QPS'],
    correct: [0],
    explanation: '10M reads/day ÷ 86,400 s/day ≈ 115.7 QPS. The classic mistake is treating 1M users as 1M requests per second — DAU must be converted through reads-per-day first.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'A common rule of thumb for peak-to-average traffic ratio is…',
    type: 'mcq',
    options: ['1–2×', '5–10×', '100×', 'There is no such rule'],
    correct: [1],
    explanation: 'Most consumer services see 5–10× average load at peak (evening hours, viral spikes). Design capacity and caching for the peak number, not the average.',
    difficulty: 1,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Scenario: 500k new items are written per day, each ~2 KB. With 5-year retention, roughly how much new storage is needed?',
    type: 'scenario',
    options: ['~1.8 TB', '~365 GB', '~18 TB', '~182 GB'],
    correct: [0],
    explanation: '500,000 × 2 KB = 1 GB/day. Over 5 years (≈1,825 days) that is ≈1.8 TB. Retention multiplies the daily write rate — never forget the time window.',
    difficulty: 2,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Which of the following are genuinely important for a back-of-the-envelope capacity plan? (select all)',
    type: 'multi',
    options: [
      'Average and peak QPS',
      'Storage growth over 5–10 years',
      'Bandwidth (bytes in/out per second)',
      'Number of git commits per day',
    ],
    correct: [0, 1, 2],
    explanation: 'QPS drives CPU and connection sizing, storage drives disk sizing, and bandwidth drives network sizing. Git commits are not a capacity input.',
    difficulty: 1,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Why do interviewers want you to round 86,400 to ~10⁵ instead of computing exactly?',
    type: 'mcq',
    options: [
      'Because it is more accurate',
      'Because order-of-magnitude math avoids false precision and is easier to sanity-check',
      'Because the interviewer prefers round numbers',
      'Because it makes storage estimates look smaller',
    ],
    correct: [1],
    explanation: 'BOTE is about the right order of magnitude to drive architecture. Exact digits imply precision you don\'t have, and round numbers let you redo the math in your head and sanity-check the result.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Approximately how many seconds are in one month?',
    type: 'mcq',
    options: ['~2.5 × 10⁶', '~3 × 10⁷', '~3.6 × 10⁴', '~2.6 × 10⁸'],
    correct: [0],
    explanation: '30 days × 86,400 ≈ 2.6M seconds, usually rounded to 2.5 × 10⁶. This is the "per month" anchor for metrics like QPS-per-month.',
    difficulty: 1,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Scenario: a system sustains 2,000 writes/sec, each ~500 bytes. Roughly how much new storage per day?',
    type: 'scenario',
    options: ['~86 GB', '~8.6 GB', '~864 MB', '~43 GB'],
    correct: [0],
    explanation: '2,000 × 500 bytes = 1 MB/s. Over 86,400 seconds that is ~86.4 GB/day. Unit discipline (bytes vs bits, per-second to per-day) is the whole game.',
    difficulty: 2,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Scenario: 100M DAU, 60% active on a given day, each active user reads 50 items, and peak is 5× average. Approximate peak read QPS?',
    type: 'scenario',
    options: ['~17k QPS', '~175k QPS', '~1.75M QPS', '~3.5M QPS'],
    correct: [1],
    explanation: 'Active users = 60M. Reads/day = 60M × 50 = 3 × 10⁹. Average = 3e9 / 1e5 ≈ 35k QPS. Peak = 5 × 35k ≈ 175k QPS. Skipping the "% active" or the peak multiplier is the classic miss.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Which unit equals 10¹² bytes?',
    type: 'mcq',
    options: ['Megabyte', 'Gigabyte', 'Terabyte', 'Petabyte'],
    correct: [2],
    explanation: 'KB (10³), MB (10⁶), GB (10⁹), TB (10¹²), PB (10¹⁵). Storage estimates usually end up in TB, which is why this ordering matters.',
    difficulty: 1,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Scenario: 10,000 reads/sec × 4 KB each. Approximate bandwidth?',
    type: 'scenario',
    options: ['40 MB/s', '4 MB/s', '400 MB/s', '40 GB/s'],
    correct: [0],
    explanation: '10,000 × 4 KB = 40,000 KB/s = 40 MB/s. Watch bytes vs bits — if the number were in bits, you would divide by 8.',
    difficulty: 2,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'What is the actual purpose of a back-of-the-envelope estimate in a design discussion?',
    type: 'mcq',
    options: [
      'To produce exact capacity figures for procurement',
      'To drive architecture decisions with order-of-magnitude numbers',
      'To show off mental arithmetic speed',
      'To replace load testing and profiling',
    ],
    correct: [1],
    explanation: 'BOTE numbers decide architecture: "400k read QPS" tells you you need a cache and CDN, not how many GB of Redis to buy. Exact numbers come later, from real traffic.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'back-of-the-envelope-estimation',
    prompt: 'Which sanity checks on an estimate are good practice? (select all)',
    type: 'multi',
    options: [
      'Compare the result to a known similar system (e.g., a mature feed does ~100k+ rps)',
      'Verify units are consistent (bytes vs bits, seconds vs days)',
      'Flag any result where peak is 1,000× the average',
      'Ask the interviewer to confirm your answer before continuing',
    ],
    correct: [0, 1, 2],
    explanation: 'Sanity checks catch order-of-magnitude errors. A 1,000× peak ratio is implausible for normal consumer traffic. You should never ask the interviewer for the answer — present your reasoning and move on.',
    difficulty: 2,
  },

  // ─── Topic 3: Latency, Throughput & Availability ───────────────────────
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Latency is best defined as…',
    type: 'mcq',
    options: [
      'The number of requests served per second',
      'The time taken to serve one request',
      'The bytes transferred per second',
      'The number of concurrent users supported',
    ],
    correct: [1],
    explanation: 'Latency is a per-request duration; throughput is the aggregate rate. They interact (throughput ≈ concurrency ÷ latency) but measure different things.',
    difficulty: 1,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Which percentile best captures "the user who actually notices the system is slow"?',
    type: 'mcq',
    options: ['P50 (median)', 'P90', 'P99', 'The mean'],
    correct: [2],
    explanation: 'The median represents the typical user, but it is the tail — P99, P999 — that people feel as "the site is slow." Averages and medians hide exactly the users who complain.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Scenario: a service reports an average latency of 50 ms but a P99 of 2 seconds. Which statement is TRUE?',
    type: 'scenario',
    options: [
      '99% of users have a great experience',
      'The average hides a bad tail — P99 is the signal to investigate',
      'The P99 is an outlier that should be ignored',
      'Latency is fine because the average is under 100 ms',
    ],
    correct: [1],
    explanation: 'An average of 50 ms with a 2 s P99 means 1 in 100 requests is miserable. Tail latency is what drives user complaints and churn — fix the tail, not the mean.',
    difficulty: 2,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Little\'s Law says L = λ × W. What happens when you raise concurrency to raise throughput past the bottleneck resource?',
    type: 'mcq',
    options: [
      'Throughput keeps rising forever',
      'Throughput plateaus and latency blows up from queueing',
      'Latency stays flat because it is independent of load',
      'The system automatically sheds load',
    ],
    correct: [1],
    explanation: 'Until the bottleneck saturates, more concurrency raises throughput. Past saturation, requests queue, so latency (W) rises and throughput stops growing. This is why over-subscribed systems feel "slow," not "broken."',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Which of the following techniques reduce tail latency? (select all)',
    type: 'multi',
    options: [
      'Setting client timeouts so one slow call cannot stall a request',
      'Issuing independent calls in parallel',
      'Using circuit breakers to fail fast when a dependency is degrading',
      'Making every dependency call serial so ordering is deterministic',
    ],
    correct: [0, 1, 2],
    explanation: 'Timeouts bound the tail, parallelism hides the latency of independent calls, and circuit breakers stop a sick dependency from dragging everything down. Serial calls multiply latency and make the tail worse.',
    difficulty: 2,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: '99.99% availability allows approximately how much downtime per year?',
    type: 'mcq',
    options: ['~8.77 hours', '~52.6 minutes', '~5.26 minutes', '~3.65 days'],
    correct: [1],
    explanation: '99.9% ≈ 8.77 h/year, 99.99% ≈ 52.6 min/year, 99.999% ≈ 5.26 min/year. Each nine removes roughly an order of magnitude of downtime.',
    difficulty: 1,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Three components, each 99.9% available, are all required for a request. The composed availability is approximately…',
    type: 'mcq',
    options: ['99.9%', '99.7%', '99.97%', '97%'],
    correct: [1],
    explanation: '0.999 × 0.999 × 0.999 ≈ 0.997 = 99.7%. Dependencies multiply availability — every required hop in the chain erodes the total. This is the core argument for decoupling.',
    difficulty: 2,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Scenario: the database is down for 30 seconds, but the site keeps serving cached (slightly stale) data. This behavior is best described as…',
    type: 'scenario',
    options: [
      'Graceful degradation',
      'Silent data loss',
      'A cache stampede',
      'Split brain',
    ],
    correct: [0],
    explanation: 'Serving stale-but-recent data during a dependency failure is graceful degradation — the availability story is "better stale than down." The cache here is doing its highest-value job.',
    difficulty: 2,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'An SLO is…',
    type: 'mcq',
    options: [
      'The measured latency percentile from production',
      'The availability or performance target you contract to',
      'The amount of downtime actually incurred last quarter',
      'A logging format for SLIs',
    ],
    correct: [1],
    explanation: 'SLI = the measurement; SLO = the target contract; error budget = 100% − SLO. Confusing SLI and SLO is a very common interview slip.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'The error budget is exhausted for the month. What does SRE practice say to do?',
    type: 'mcq',
    options: [
      'Ship more changes to recover revenue quickly',
      'Freeze risky releases and focus on stability',
      'Loosen the SLO so the budget resets',
      'Silence the alert so it stops bothering people',
    ],
    correct: [1],
    explanation: 'The error budget is the permission to ship risk. When it is spent, the correct move is to slow down change and restore stability — not to move the goalposts or hide the alert.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Which of the following are required to move from 99.9% to 99.99% availability? (select all)',
    type: 'multi',
    options: [
      'Automatic failover (not manual paging)',
      'Regularly tested failover drills',
      'Monitoring that detects failure faster than users do',
      'A human on call for every alert, even cosmetic ones',
    ],
    correct: [0, 1, 2],
    explanation: '99.99% allows ~52 minutes of downtime a year. Manual failover alone can\'t hit that — you need automation, drills, and fast detection. Page-loads-per-alert should go down, not up.',
    difficulty: 2,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: '"Each nine is an order of magnitude harder" means…',
    type: 'mcq',
    options: [
      'Cost and engineering effort rise roughly 10× per nine',
      'Nines are essentially free once you are at 99%',
      '99.99% is exactly 4× harder than 99.9%',
      'It only applies to database uptime',
    ],
    correct: [0],
    explanation: 'Downtime drops by ~10× per nine, and the systems work to shave it — redundancy, automation, testing, multi-region — scales similarly. Realistic targets are usually 99.9–99.99%.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'latency-throughput-availability',
    prompt: 'Scenario: the health check only pings a homepage that is served entirely from the CDN cache. The dashboard shows 100% availability. Why is this misleading?',
    type: 'scenario',
    options: [
      'The health check does not measure user-perceived availability of the whole system',
      'It is not misleading — CDN-cached homepages are the product',
      'The health check should ping the database instead of the homepage',
      'Availability is correctly reported; the CDN never fails',
    ],
    correct: [0],
    explanation: 'A health check on a CDN-cached page never exercises the app or database, so it reports green while the actual product (login, checkout, dynamic pages) is down. An SLI must measure the user\'s real path.',
    difficulty: 3,
    isTricky: true,
  },
  // ─── Topic 4: CAP & Consistency Models ────────────────────────────────
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'During a network partition, CAP says a distributed system must choose between…',
    type: 'mcq',
    options: [
      'Consistency and Availability',
      'Consistency and Partition tolerance',
      'Availability and Partition tolerance',
      'All three — modern systems get everything',
    ],
    correct: [0],
    explanation: 'Partitions are not optional (P is forced), so the real choice during a partition is between serving every request (Availability) and serving the latest data (Consistency).',
    difficulty: 1,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'A system advertised as "CA" (consistent AND available) is best described as…',
    type: 'mcq',
    options: [
      'The ideal — always pick CA',
      'Only possible when the network is healthy; during a partition it is actually CP or AP',
      'The same as eventually consistent',
      'CA means it tolerates no partitions and is therefore useless',
    ],
    correct: [1],
    explanation: 'Networks will partition. So every real system is CP or AP during a partition, and "CA" only describes behavior when the network is healthy. The P is not a choice.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Scenario: a payment/checkout system during a partition. The right preference is CP because…',
    type: 'scenario',
    options: [
      'Users must always be able to read stale carts',
      'Charging the same card twice is worse than a failed request — refuse writes rather than diverge',
      'CP is automatically faster',
      'Checkout does not need consistency',
    ],
    correct: [1],
    explanation: 'Money movement must not double-charge or silently diverge. A CP system fails the write cleanly when it cannot guarantee correctness; an AP system might accept it twice.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Scenario: a "like" button on a social post during a partition. Choosing AP is justified because…',
    type: 'scenario',
    options: [
      'Like counts must be exactly-once and ordered',
      'A slightly stale like count is acceptable; returning a 500 error is worse',
      'AP is strictly stronger than CP',
      'Likes are stored with ACID transactions',
    ],
    correct: [1],
    explanation: 'AP systems keep accepting writes and reconcile later. For low-stakes, mergeable state like like-counts, availability beats perfect freshness.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'PACELC extends CAP by adding a second trade-off. What is it?',
    type: 'mcq',
    options: [
      'Else (healthy network): Latency vs Consistency',
      'Async replication for every write',
      'Load balancing at the edge',
      'Exactly-once delivery everywhere',
    ],
    correct: [0],
    explanation: 'PACELC: Partition → Availability vs Consistency; Else (no partition) → Latency vs Consistency. Even in a healthy network, synchronous replication to be consistent adds latency.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Which of the following are properties of strong (linearizable) consistency? (select all)',
    type: 'multi',
    options: [
      'Every read returns the result of the latest completed write',
      'A read may return data that predates an acknowledged write',
      'All operations appear in a single global order',
      'Replicas converge to a value eventually, at their own pace',
    ],
    correct: [0, 2],
    explanation: 'Linearizability gives you a global order and never lets a read see "older than the latest write." Eventual consistency explicitly allows stale reads and slow convergence.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Causal consistency guarantees that…',
    type: 'mcq',
    options: [
      'Every read is the very latest write',
      'If write B is caused by write A, any reader who sees B also sees A',
      'All writes across all nodes are totally ordered',
      'Concurrent writes never conflict',
    ],
    correct: [1],
    explanation: 'Causal consistency preserves cause-effect order (a reply follows its post) but allows unrelated writes to appear in any order. It matches human intuition and is usually good enough for feeds.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Last-write-wins (LWW) conflict resolution…',
    type: 'mcq',
    options: [
      'Correctly merges concurrent updates',
      'Can silently drop a concurrent update based on timestamps',
      'Requires vector clocks',
      'Is only used in CP systems',
    ],
    correct: [1],
    explanation: 'LWW keeps the write with the latest timestamp and discards the other — so a genuinely concurrent update can be silently lost. Vector clocks detect concurrency instead of guessing by clock.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Which statement about ACID vs BASE is TRUE?',
    type: 'mcq',
    options: [
      'BASE trades strong consistency for availability and partition tolerance',
      'BASE stands for "Basic Availability, Soft Events"',
      'ACID systems cannot scale at all',
      'BASE is simply wrong and should never be used',
    ],
    correct: [0],
    explanation: 'BASE (Basically Available, Soft state, Eventually consistent) is a different contract, not a lesser one: it prioritizes availability and lets the application handle eventual convergence.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Scenario: after a transfer, the app reads the user\'s balance to display it. Which read does money movement require?',
    type: 'scenario',
    options: [
      'A strong/quorum read that reflects acknowledged writes',
      'A read from any stale cache',
      'An eventual read from any replica',
      'No read — the balance is just an estimate',
    ],
    correct: [0],
    explanation: 'For critical data, use the consistency level that matches the risk: a quorum or primary read for balances. Stale reads belong to display-only, low-stakes data.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Vector clocks are used to…',
    type: 'mcq',
    options: [
      'Detect concurrent updates so conflicts can be merged rather than guessed',
      'Replace all wall-clock timestamps',
      'Guarantee linearizable reads',
      'Speed up read-heavy workloads',
    ],
    correct: [0],
    explanation: 'Vector clocks track causal history per replica. If two updates are concurrent, the vector clock shows it and the application can merge instead of silently dropping one.',
    difficulty: 2,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'A single-node relational database in CAP terms is best described as…',
    type: 'mcq',
    options: [
      'Not subject to the CAP partition trade-off — with no partition there is no CP/AP choice; it is consistent and available while up',
      'Always CP',
      'Always AP',
      'CA, which proves CA is possible under partitions',
    ],
    correct: [0],
    explanation: 'CAP is about *distributed* systems under partition. A single node has no partition, so it can be both consistent and available — CAP does not apply the same way. This is why "CA exists" is a category error.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cap-and-consistency-models',
    prompt: 'Which of the following are typically AP (availability-first) systems? (select all)',
    type: 'multi',
    options: ['Cassandra', 'DynamoDB', 'ZooKeeper', 'DNS'],
    correct: [0, 1, 3],
    explanation: 'Cassandra and DynamoDB are Dynamo-style AP systems; DNS famously serves stale data rather than failing. ZooKeeper (ZAB) is CP — it would rather refuse the majority\'s requests than serve divergent data.',
    difficulty: 2,
    isTricky: true,
  },

  // ─── Topic 5: Load Balancing ───────────────────────────────────────────
  {
    topicSlug: 'load-balancing',
    prompt: 'An L4 load balancer makes routing decisions based on…',
    type: 'mcq',
    options: [
      'IP address and TCP/UDP port',
      'HTTP path and headers',
      'Cookies and session data',
      'Database query text',
    ],
    correct: [0],
    explanation: 'L4 operates at the transport layer — it forwards whole connections based on IP/port. L7 understands HTTP and can route by path, host, and headers.',
    difficulty: 1,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Which capability is possible at L7 but NOT at L4?',
    type: 'mcq',
    options: [
      'Routing requests by URL path and host',
      'Forwarding TCP traffic',
      'Performing TCP health checks',
      'Handling a high volume of raw connections',
    ],
    correct: [0],
    explanation: 'Path/host/header-aware routing requires parsing the HTTP protocol, which is L7. L4 is fast but content-blind.',
    difficulty: 1,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Which of the following are valid load-balancing algorithms? (select all)',
    type: 'multi',
    options: [
      'Round robin',
      'Weighted round robin',
      'Least connections',
      'Bubble sort',
    ],
    correct: [0, 1, 2],
    explanation: 'Round robin, weighted RR, least connections, least response time, and IP hash are all real algorithms. Bubble sort is a sorting algorithm — it has nothing to do with routing.',
    difficulty: 1,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Scenario: you bought 2× faster servers alongside older ones. Which algorithm uses the extra capacity best?',
    type: 'scenario',
    options: [
      'Weighted round robin (higher weight for faster servers)',
      'Strict FIFO',
      'Round robin treating all servers equally',
      'Random with equal probability',
    ],
    correct: [0],
    explanation: 'Weighted algorithms send proportionally more traffic to machines with more capacity. Equal round robin would underuse the fast servers and overload the slow ones.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Sticky sessions (session affinity) are best described as…',
    type: 'mcq',
    options: [
      'The recommended way to run stateless backends',
      'A workaround for stateful servers — the real fix is making servers stateless',
      'Required for HTTPS to work',
      'An L4-only feature',
    ],
    correct: [1],
    explanation: 'Sticky sessions pin a user to one server, which breaks elasticity and failover. If you push state into a shared store, any server can serve any user and stickiness becomes unnecessary.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'A health-check endpoint that itself queries the database. Why is this a problem?',
    type: 'mcq',
    options: [
      'It is slightly slower, which is acceptable',
      'A database blip makes every backend "unhealthy", so the LB fails ALL traffic at once',
      'Database queries are forbidden inside health checks',
      'It is fine — health checks should test the full stack',
    ],
    correct: [1],
    explanation: 'The health check should answer "can this server take traffic?" — not "is the whole platform healthy?" A DB dependency in the health check turns one DB blip into a total outage.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Scenario: during every deploy, users get 502 errors because connections are cut mid-request. The fix is to…',
    type: 'scenario',
    options: [
      'Drain the server first: stop new traffic, let in-flight requests finish, then terminate',
      'Deploy faster so the window is shorter',
      'Add more servers during deploy',
      'Disable health checks during deploys',
    ],
    correct: [0],
    explanation: 'Graceful draining marks a server unhealthy, stops new connections, waits for in-flight requests (drain window), and only then kills the process. Instant kills mid-request are the classic deploy-causes-502 smell.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'With L7 TLS termination at the load balancer, traffic between the LB and backends is…',
    type: 'mcq',
    options: [
      'Plaintext — protect the backend network with mTLS or a private subnet',
      'Always encrypted end-to-end',
      'Encrypted but clients see backend certificates',
      'Not possible to send',
    ],
    correct: [0],
    explanation: 'The LB decrypts TLS and typically forwards plaintext to backends over the internal network. Without mTLS or a private subnet, an attacker who reaches the internal network can sniff traffic.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'How does "least response time" differ from "least connections"?',
    type: 'mcq',
    options: [
      'It factors in observed latency, not just the connection count',
      'They are identical',
      'Least connections is always superior',
      'Response time ignores server load entirely',
    ],
    correct: [0],
    explanation: 'Connections alone miss how slow each server is. Least response time routes to the server with the best combination of connections and observed latency — better for variable workloads.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Which of the following are health-check mechanisms? (select all)',
    type: 'multi',
    options: [
      'An HTTP probe such as GET /healthz',
      'A TCP connect probe',
      'Passive tracking of connection failures and 5xx rates',
      'A human reading server logs at 3am',
    ],
    correct: [0, 1, 2],
    explanation: 'Active probes (HTTP, TCP) and passive observation (error rates) both remove unhealthy servers from rotation automatically. Manual log reading is not a health check.',
    difficulty: 1,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Scenario: two load balancers run active/passive behind a floating VIP. The passive LB…',
    type: 'scenario',
    options: [
      'Monitors the active LB and takes over the VIP if it fails',
      'Is unused dead weight',
      'Serves half the traffic in parallel',
      'Stores the database writes',
    ],
    correct: [0],
    explanation: 'Active/passive means one LB owns the VIP while the standby health-checks it and can assume the VIP on failure. This removes the load balancer itself as a single point of failure.',
    difficulty: 1,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'IP-hash load balancing (pinning a client to a server) is most useful when…',
    type: 'mcq',
    options: [
      'Backends hold per-user cache or state that benefits from locality',
      'Servers are stateless and interchangeable',
      'You need path-based routing',
      'Traffic is uniformly distributed',
    ],
    correct: [0],
    explanation: 'Hash affinity gives cache or session locality — the same client hits the same server, so its local cache stays warm. Stateless designs do not need it and generally prefer least-connections.',
    difficulty: 2,
  },
  {
    topicSlug: 'load-balancing',
    prompt: 'Given fully stateless, equal-capacity backends, which algorithm is the sensible default?',
    type: 'mcq',
    options: [
      'Least connections (or round robin)',
      'Sticky cookie pinning',
      'IP hash with affinity',
      'Weighted round robin with arbitrary weights',
    ],
    correct: [0],
    explanation: 'With interchangeable backends you want the least-loaded server: least connections (or round robin). Stickiness and weights only add value when state or heterogeneity exists.',
    difficulty: 2,
    isTricky: true,
  },

  // ─── Topic 6: Caching ──────────────────────────────────────────────────
  {
    topicSlug: 'caching',
    prompt: 'In cache-aside, the write path is…',
    type: 'mcq',
    options: [
      'Write to the database, then update the cache',
      'Write to the database, then invalidate (delete) the cache entry',
      'Write only to the cache',
      'Write-through to both atomically',
    ],
    correct: [1],
    explanation: 'Cache-aside invalidates on write and loads lazily on the next read. Updating the cache on write (instead of invalidating) opens the door to interleaving races that leave stale data.',
    difficulty: 1,
  },
  {
    topicSlug: 'caching',
    prompt: 'Which is safer against concurrent-writer races: updating the cache on write, or invalidating it?',
    type: 'mcq',
    options: [
      'Updating — the cache stays fresher',
      'Invalidating — two concurrent updaters can interleave and leave stale data, but a delete is a no-op race-wise',
      'They are equally safe',
      'Never invalidate; always use TTLs',
    ],
    correct: [1],
    explanation: 'Two writers "update the cache" can each write a stale value after the other (last-writer-wins with old data). Invalidating on write means the next read simply fetches fresh from the DB.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'caching',
    prompt: 'Scenario: a hot key expires, thousands of concurrent requests miss, and the database melts. This is called…',
    type: 'scenario',
    options: [
      'A cache stampede (thundering herd)',
      'Cache poisoning',
      'A cold start',
      'Write-back failure',
    ],
    correct: [0],
    explanation: 'A stampede is when many requests miss simultaneously and all hit the backend. It is the most common way a "cache" makes things *worse* for hot keys.',
    difficulty: 1,
  },
  {
    topicSlug: 'caching',
    prompt: 'Which of the following mitigate cache stampedes? (select all)',
    type: 'multi',
    options: [
      'Request coalescing / locks so one request refreshes while others wait',
      'Probabilistic early expiration — refresh near expiry with randomness',
      'Adding jitter to TTLs so keys do not expire together',
      'Making the cache unbounded so nothing ever expires',
    ],
    correct: [0, 1, 2],
    explanation: 'Coalescing, early expiration, and TTL jitter all break the synchronized-miss pattern. An unbounded cache is not a fix — it is an eviction failure that grows memory without bound.',
    difficulty: 2,
  },
  {
    topicSlug: 'caching',
    prompt: 'LRU eviction removes…',
    type: 'mcq',
    options: [
      'The most recently used entry',
      'The least recently used entry',
      'The least frequently used entry',
      'The newest entry',
    ],
    correct: [1],
    explanation: 'LRU (Least Recently Used) evicts the entry whose access is oldest. It assumes "recently accessed ⇒ likely accessed again."',
    difficulty: 1,
  },
  {
    topicSlug: 'caching',
    prompt: 'When does LFU (least frequently used) beat LRU?',
    type: 'mcq',
    options: [
      'When popularity is stable and there are no big bursty access patterns',
      'When traffic is extremely bursty',
      'It never beats LRU',
      'When entries expire by TTL',
    ],
    correct: [0],
    explanation: 'LFU tracks access *frequency*, which fits stable popularity (videos, product pages). Bursty or one-off spikes can pollute LFU, where LRU would have evicted the stale burst long ago.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'caching',
    prompt: 'Scenario: 1M keys are created together in a batch and all share the same TTL. At TTL expiry…',
    type: 'scenario',
    options: [
      'They all expire at once and cause a stampede on the next reads',
      'TTLs automatically stagger',
      'LRU protects against the expiry',
      'It is harmless — TTL expiry is never an issue',
    ],
    correct: [0],
    explanation: 'Identical TTLs on batch-created keys synchronize their expiry — a coordinated stampede. Add random jitter so expiries spread out over time.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'caching',
    prompt: 'The main risk of write-back (write-behind) caching is…',
    type: 'mcq',
    options: [
      'Losing acknowledged data if the cache dies before it flushes to the DB',
      'Very high read latency',
      'An empty cache after a restart',
      'None — it is strictly better than cache-aside',
    ],
    correct: [0],
    explanation: 'Write-back acknowledges the write immediately and flushes later. If the cache crashes before the flush, that data is gone — so it is only for loss-tolerant data (counters, analytics) unless backed by a durable log.',
    difficulty: 2,
  },
  {
    topicSlug: 'caching',
    prompt: 'A TTL is best understood as…',
    type: 'mcq',
    options: [
      'A bound on staleness — not a substitute for explicit invalidation',
      'The same thing as explicit invalidation',
      'A security control',
      'Something you should never use',
    ],
    correct: [0],
    explanation: 'TTL caps how stale a cache entry can be, but fresh data that changes (profile updates) needs explicit invalidation. Using only TTLs means users can see stale data for the whole TTL window.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'caching',
    prompt: 'Which of the following are good cache-key hygiene practices? (select all)',
    type: 'multi',
    options: [
      'Include everything that affects the response (auth context, tenant, locale)',
      'Normalize user-controlled input that ends up in the key',
      'Cap key cardinality so attackers cannot blow up memory',
      'Use only the raw URL path with no parameters',
    ],
    correct: [0, 1, 2],
    explanation: 'Keys must capture every input that changes the response, or you get cross-user cache poisoning. Normalizing input and capping cardinality stop "cache key blow-up" attacks.',
    difficulty: 2,
  },
  {
    topicSlug: 'caching',
    prompt: 'Scenario: user A\'s personalized response is served to user B. The most likely cause is…',
    type: 'scenario',
    options: [
      'The cache key omitted the user/auth context',
      'LRU evicted the wrong entry',
      'Write-back delay',
      'The TTL was too short',
    ],
    correct: [0],
    explanation: 'Serving one user\'s private response to another is cache poisoning via a bad key. Anything that varies per user — user id, auth token, role — must be part of the key (or excluded from shared caches entirely).',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'caching',
    prompt: 'Which of the following is a valid cache eviction policy?',
    type: 'mcq',
    options: ['FIFO', 'DNS', 'ACID', 'BASE'],
    correct: [0],
    explanation: 'FIFO (first-in, first-out), LRU, and LFU are real eviction policies. DNS is a naming system; ACID and BASE are transaction/consistency models.',
    difficulty: 1,
  },
  {
    topicSlug: 'caching',
    prompt: 'Scenario: cache hit ratio is 99%, but the database is still melting. Is this plausible?',
    type: 'scenario',
    options: [
      'Yes — the 1% misses may be the most expensive queries or the hottest keys',
      'No — 99% hit ratio guarantees the DB is fine',
      'Only if there is a software bug',
      'No — a cache always reduces DB load proportionally',
    ],
    correct: [0],
    explanation: 'Hit ratio measures *count*, not *cost*. If the misses are heavy scans, expensive joins, or a hot key that evicts quickly, a 99% ratio can still saturate the DB. Measure query cost, not just hit rate.',
    difficulty: 3,
    isTricky: true,
  },
  // ─── Topic 7: Databases ──────────────────────────────────────────────
  {
    topicSlug: 'databases',
    prompt: 'What does ACID stand for in relational databases?',
    type: 'mcq',
    options: [
      'Atomicity, Consistency, Isolation, Durability',
      'Availability, Consistency, Integrity, Distribution',
      'Atomicity, Concurrency, Indexing, Durability',
      'Alignment, Cohesion, Isolation, Deduplication',
    ],
    correct: [0],
    explanation: 'ACID is Atomicity, Consistency, Isolation, Durability — the guarantees a transactional relational database provides. The other options mix in unrelated words.',
    difficulty: 1,
    isTricky: false,
  },
  {
    topicSlug: 'databases',
    prompt: 'Which storage engine is generally more WRITE-optimized?',
    type: 'mcq',
    options: ['B-tree', 'LSM-tree', 'Heap file', 'Inverted index'],
    correct: [1],
    explanation: 'LSM-trees buffer writes in memory and flush them as sequential SSTables, minimizing random I/O — great for write-heavy workloads. B-trees are read-optimized but do random writes.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'You add a secondary index to a hot write table. What is the most likely effect?',
    type: 'scenario',
    options: [
      'Reads get slower and writes get faster',
      'Reads for that column get faster, but writes get slower',
      'Both reads and writes get faster',
      'Writes become atomic automatically',
    ],
    correct: [1],
    explanation: 'An index speeds lookups on that column, but every insert/update must also maintain it, so writes get slower. This is the classic index trade-off.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'Which of the following are good reasons to choose a NoSQL (non-relational) database? (select all)',
    type: 'multi',
    options: [
      'Highly flexible or changing schema',
      'Need to scale writes across many nodes',
      'Need complex multi-table joins',
      'Very high write throughput with simple key access',
    ],
    correct: [0, 1, 3],
    explanation: 'NoSQL shines with flexible schemas and scale-out write throughput. Complex joins are a relational strength — a NoSQL system usually cannot do them efficiently.',
    difficulty: 2,
  },
  {
    topicSlug: 'databases',
    prompt: 'A read-heavy application has one database that is now the bottleneck. Which is the FIRST scaling step that preserves correctness?',
    type: 'scenario',
    options: [
      'Shard the database by user_id',
      'Add read replicas and route reads to them',
      'Move to a document database',
      'Cache every query result with no TTL',
    ],
    correct: [1],
    explanation: 'Read replicas scale read throughput directly while the primary keeps handling writes — the natural first step for a read-heavy workload. Sharding is more drastic; caching without TTL risks stale data.',
    difficulty: 2,
  },
  {
    topicSlug: 'databases',
    prompt: 'Why does connection pooling help a database under load?',
    type: 'mcq',
    options: [
      'It increases the database\'s CPU capacity',
      'It reuses open connections instead of opening one per request',
      'It shards the data automatically',
      'It caches query results',
    ],
    correct: [1],
    explanation: 'Opening a TCP connection per request is expensive. A pool keeps a set of ready connections, cutting connection-setup overhead and limiting connection churn.',
    difficulty: 1,
  },
  {
    topicSlug: 'databases',
    prompt: 'Denormalization trades what for what?',
    type: 'mcq',
    options: [
      'Write speed for read safety',
      'Duplicated/stale-prone data for faster reads',
      'Schema flexibility for integrity',
      'Storage for CPU',
    ],
    correct: [1],
    explanation: 'Denormalization stores redundant copies (e.g. a denormalized count) to make reads fast, at the cost of duplication and the need to keep copies in sync.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'Why are LSM-trees favored for write-heavy time-series workloads?',
    type: 'mcq',
    options: [
      'They keep all data in memory permanently',
      'They convert random writes into sequential append-style writes',
      'They never need compaction',
      'They support joins natively',
    ],
    correct: [1],
    explanation: 'LSM buffers writes and flushes them as sequential SSTables with periodic compaction, so the disk sees largely sequential writes — ideal for append-heavy data like time series.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'Which of the following are TRUE of a secondary index? (select all)',
    type: 'multi',
    options: [
      'It speeds up lookups on the indexed column',
      'It must be maintained on every write',
      'It is only stored in RAM',
      'It can increase write amplification',
    ],
    correct: [0, 1, 3],
    explanation: 'A secondary index accelerates reads on that column but adds write overhead (and amplification). It is persisted, not RAM-only.',
    difficulty: 2,
  },
  {
    topicSlug: 'databases',
    prompt: 'A document database like MongoDB is best described as a…',
    type: 'mcq',
    options: [
      'Columnar database optimized for analytics',
      'Graph database for relationships',
      'Flexible-schema database storing JSON-like documents',
      'In-memory cache with persistence',
    ],
    correct: [2],
    explanation: 'MongoDB stores BSON/JSON-like documents with flexible schemas. It is not columnar, not graph-oriented, and not an in-memory cache.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'A read replica serves stale data. The most likely cause is…',
    type: 'mcq',
    options: [
      'The replica is in a different availability zone',
      'Replication lag from the primary to the async replica',
      'The replica has fewer CPUs',
      'The application cached the response',
    ],
    correct: [1],
    explanation: 'With asynchronous replication, replicas trail the primary by some lag, so they can serve data a few moments old. That is normal for async replicas.',
    difficulty: 2,
  },
  {
    topicSlug: 'databases',
    prompt: 'Fully normalizing a schema (3NF) most directly costs you…',
    type: 'mcq',
    options: [
      'Data integrity',
      'Write performance in the form of more joins and more queries',
      'Security',
      'Backup size',
    ],
    correct: [1],
    explanation: 'Normalization removes duplication and preserves integrity, but queries now join across many tables — more and heavier read queries. It is a read/write trade-off, not a security one.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'databases',
    prompt: 'Which database type would you pick for storing relationships you must traverse many levels deep (e.g. social graph)?',
    type: 'mcq',
    options: ['Document DB', 'Graph DB', 'Wide-column DB', 'In-memory KV store'],
    correct: [1],
    explanation: 'Graph databases make multi-hop relationship traversal natural and fast, which is exactly what social graphs, fraud detection, and recommendation graphs need.',
    difficulty: 1,
  },

  // ─── Topic 8: Sharding & Partitioning ────────────────────────────────
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'What problem does sharding primarily solve?',
    type: 'mcq',
    options: [
      'High network latency',
      'Data size or write throughput exceeding a single node',
      'Slow application code',
      'DNS resolution failures',
    ],
    correct: [1],
    explanation: 'Sharding spreads data and writes across many nodes, so no single node holds all the data or absorbs all the write load.',
    difficulty: 1,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'You shard a messages table by created_at ranges. What is the likely hotspot?',
    type: 'scenario',
    options: [
      'An even spread across all shards',
      'The most recent shard receiving almost all writes',
      'The oldest shard getting all reads',
      'No hotspot — range sharding is always balanced',
    ],
    correct: [1],
    explanation: 'Range sharding on a monotonically increasing key concentrates new writes on one shard — the classic hotspot. Hash sharding avoids this at the cost of range queries.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'What is the main benefit of consistent hashing over modulo-N sharding?',
    type: 'mcq',
    options: [
      'It always keeps data perfectly balanced',
      'Adding/removing nodes only moves a small fraction of keys',
      'It eliminates the need for replication',
      'It makes range queries across shards possible',
    ],
    correct: [1],
    explanation: 'With modulo-N, changing N rehashes most keys. Consistent hashing maps keys to a ring so only the keys on the affected arc move when nodes join or leave.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'Virtual nodes (vnodes) in consistent hashing primarily improve…',
    type: 'mcq',
    options: [
      'Security of the hash function',
      'Load balance and smoother rebalancing when few nodes exist',
      'Query speed of the database',
      'Data durability',
    ],
    correct: [1],
    explanation: 'Each physical node gets many virtual positions on the ring, so key distribution is much more even and adding/removing nodes moves less data at once.',
    difficulty: 2,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'A 5 TB user table needs sharding. Which shard key is the best default?',
    type: 'scenario',
    options: ['created_at', 'email_domain', 'user_id (hash)', 'country'],
    correct: [2],
    explanation: 'Hashing user_id gives an even, stable distribution and matches the common access pattern (lookup by user). created_at and country skew; email_domain concentrates on big providers.',
    difficulty: 2,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'A single celebrity user accounts for 40% of reads. Which problem is this?',
    type: 'mcq',
    options: ['Shard churn', 'Hot key / hotspot', 'Rebalancing', 'Replication lag'],
    correct: [1],
    explanation: 'A disproportionately popular key lands on one shard and overwhelms it — the hot-key problem. Mitigations include replication of the hot key or a second-level cache.',
    difficulty: 2,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'Which of the following become harder after sharding? (select all)',
    type: 'multi',
    options: [
      'Cross-shard joins',
      'Distributed transactions spanning shards',
      'Serving a single huge range scan',
      'Duplicating data across availability zones',
    ],
    correct: [0, 1, 2],
    explanation: 'Sharding splits both data and indexes, so joins, transactions, and big range scans now cross shards. Zone replication is orthogonal — you still replicate each shard.',
    difficulty: 2,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'Why is modulo-N (e.g. user_id % 4) sharding awkward to change?',
    type: 'mcq',
    options: [
      'Modulo is slow',
      'Changing N rehashes and moves most keys to different shards',
      'Modulo only works on strings',
      'It cannot be used with replication',
    ],
    correct: [1],
    explanation: 'If you go from 4 to 5 shards, user_id % 5 puts most keys on a different shard than user_id % 4, forcing a near-total migration. Consistent hashing avoids this.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'In a consistent-hashing ring, when one node is removed, which keys move?',
    type: 'mcq',
    options: [
      'All keys',
      'Only keys that hash to that node\'s arc (and are reassigned to its successor)',
      'No keys — data stays put',
      'Keys in other nodes are rebalanced too',
    ],
    correct: [1],
    explanation: 'Only the removed node\'s keys need a new home; they go to the successor on the ring. That is exactly why consistent hashing keeps churn minimal.',
    difficulty: 2,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'Secondary indexes in a sharded database are tricky because…',
    type: 'mcq',
    options: [
      'They are encrypted',
      'Each shard only has an index over its own slice, so global lookups need scatter-gather',
      'They cannot be built at all',
      'They are always in-memory',
    ],
    correct: [1],
    explanation: 'A local secondary index only covers that shard. A query on a non-shard-key column must fan out to every shard (scatter-gather), then merge — expensive.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'What does "rebalancing" mean when shards get uneven?',
    type: 'mcq',
    options: [
      'Restarting the database',
      'Moving data between shards to even out load and storage',
      'Rehashing all keys every minute',
      'Adding more replicas of each shard',
    ],
    correct: [1],
    explanation: 'Rebalancing migrates data from overloaded shards to underloaded ones. It must be done incrementally without stopping traffic.',
    difficulty: 1,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'For a globally distributed service, what shard key gives both locality and balance?',
    type: 'scenario',
    options: [
      'user_id only',
      'Region prefix + user_id (composite key)',
      'created_at only',
      'A random UUID with no locality',
    ],
    correct: [1],
    explanation: 'A composite key like (region, user_id) keeps a user\'s data in their region (locality) while still distributing across shards. This is a common geo-aware sharding pattern.',
    difficulty: 3,
  },
  {
    topicSlug: 'sharding-and-partitioning',
    prompt: 'True or false: hash sharding guarantees no shard will ever be overloaded.',
    type: 'mcq',
    options: [
      'True — hashing always distributes perfectly',
      'False — hot keys and skewed values can still overload one shard',
      'True — but only with consistent hashing',
      'False — hash sharding always has one hot shard',
    ],
    correct: [1],
    explanation: 'Hash sharding spreads by key, but if a few keys dominate (hot keys) or values are skewed, those shards still overload. Hashes smooth skew; they do not remove it.',
    difficulty: 2,
    isTricky: true,
  },

  // ─── Topic 9: Replication & Consensus ─────────────────────────────────
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'With asynchronous replication, what is the biggest risk if the leader crashes?',
    type: 'scenario',
    options: [
      'No risk — replicas are always in sync',
      'The most recently committed writes that only the leader held can be lost',
      'Reads become slower permanently',
      'The database becomes unavailable forever',
    ],
    correct: [1],
    explanation: 'Async replication acknowledges writes on the leader before they reach replicas. If the leader fails before propagating, those writes are lost even though clients were told they committed.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'Synchronous replication guarantees…',
    type: 'mcq',
    options: [
      'Lower write latency',
      'The write is committed on the leader and at least one follower before the client is acknowledged',
      'Reads are always routed to the follower',
      'No network round trips',
    ],
    correct: [1],
    explanation: 'Sync replication waits for a follower to persist the write before acknowledging — strong durability but higher latency.',
    difficulty: 2,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'A quorum of W + R > N (with N replicas) tolerates how many replica failures?',
    type: 'mcq',
    options: [
      'N - 1',
      'At least N - max(W, R) + 1 of the replicas can fail and still serve',
      'Zero failures',
      'Only the leader can fail',
    ],
    correct: [1],
    explanation: 'Quorum reads/writes guarantee overlapping nodes: as long as W writes and R reads each reach distinct nodes such that W + R > N, a minority (up to N - max(W,R)) of nodes can fail.',
    difficulty: 3,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'You just wrote a comment, refresh, and do not see it. The most likely cause is…',
    type: 'scenario',
    options: [
      'The write failed',
      'Your read went to an async replica that had not caught up',
      'The database is down',
      'The comment was rejected for spam',
    ],
    correct: [1],
    explanation: 'With async replication, a read can hit a lagging replica and miss the just-written data — a read-your-writes violation. Solutions include reading from the leader or sticky reads.',
    difficulty: 2,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'What is "split-brain"?',
    type: 'mcq',
    options: [
      'Two leaders both accepting writes, producing divergent data',
      'A node that cannot reach the leader',
      'Data duplicated across regions',
      'A network that drops packets',
    ],
    correct: [0],
    explanation: 'A partition can cause two nodes to both believe they are leader, so both accept writes that never reconcile. Consensus and fencing/epoch numbers exist to prevent this.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'A fencing/epoch token prevents…',
    type: 'mcq',
    options: [
      'Duplicate reads',
      'A demoted leader from continuing to accept writes',
      'Data compression',
      'Slow queries',
    ],
    correct: [1],
    explanation: 'When a new leader is elected, it gets a higher epoch. A node holding a stale (lower) epoch is rejected if it tries to act as leader — preventing the old leader from causing divergence.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'Which of the following are goals of a consensus algorithm like Raft? (select all)',
    type: 'multi',
    options: [
      'Single leader election',
      'Ordered log replication across nodes',
      'Guaranteeing the network never partitions',
      'Safety: only committed, consistent decisions are agreed on',
    ],
    correct: [0, 1, 3],
    explanation: 'Raft elects one leader, replicates an ordered log, and guarantees safety even under failures. It cannot prevent network partitions — it survives them.',
    difficulty: 2,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'Read replicas help with… (select all)',
    type: 'multi',
    options: [
      'Scaling read throughput',
      'High availability of reads',
      'Lower write latency',
      'Guaranteeing read-after-write consistency',
    ],
    correct: [0, 1],
    explanation: 'Replicas scale reads and keep reads available if the leader fails. They do not make writes faster and, being async, do not guarantee you read your own latest write.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'In leaderless (Dynamo-style) replication with N=3, W=2, R=2, how many nodes can fail and still serve reads and writes?',
    type: 'scenario',
    options: ['0', '1', '2', '3'],
    correct: [1],
    explanation: 'With W=2 and R=2 over N=3, any write reaches 2 nodes and any read covers 2 nodes, and the read quorum overlaps the write quorum. One node can fail; two would break the overlap.',
    difficulty: 3,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'What does linearizability (strong consistency) guarantee?',
    type: 'mcq',
    options: [
      'Reads return the most recently written value, as if there were one copy',
      'Reads eventually converge after some seconds',
      'Reads are always from the nearest node',
      'Writes are batched',
    ],
    correct: [0],
    explanation: 'Linearizability makes a distributed system behave like a single machine: once a write completes, every subsequent read (from any node) sees it. It is the strongest common guarantee.',
    difficulty: 2,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'Multi-leader replication is most useful for…',
    type: 'mcq',
    options: [
      'Single-region setups with one write node',
      'Multiple data centers where each region accepts local writes',
      'Read-heavy workloads with one writer',
      'Replacing a cache',
    ],
    correct: [1],
    explanation: 'Multi-leader lets each data center accept local writes (low latency per region) and syncs them, at the cost of handling write conflicts between leaders.',
    difficulty: 2,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'Which is NOT a consequence of replication lag?',
    type: 'mcq',
    options: [
      'A user sees stale data on a replica',
      'Monotonic-read violations',
      'Permanent data corruption',
      'Read-your-writes violations',
    ],
    correct: [2],
    explanation: 'Lag causes temporary staleness and ordering anomalies, but not corruption — the data on replicas is eventually the same. Corruption would be a different kind of bug.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'replication-and-consensus',
    prompt: 'A quorum system with W + R > N still does NOT by itself guarantee…',
    type: 'mcq',
    options: [
      'That reads see recent writes under certain concurrent conditions',
      'Durability of writes',
      'Tolerance of N/2 failures',
      'Faster writes',
    ],
    correct: [0],
    explanation: 'Quorum overlap gives good guarantees but without things like read repair, monotonic clocks, or session consistency, concurrent or lagging updates can still produce anomalies. And quorums do not speed up writes.',
    difficulty: 3,
    isTricky: true,
  },

  // ─── Topic 10: Message Queues & Async ─────────────────────────────────
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'What does introducing a message queue actually give you?',
    type: 'mcq',
    options: [
      'Faster end-to-end latency',
      'Decoupling, buffering of bursts, and independent scaling',
      'Guaranteed exactly-once processing',
      'A replacement for the database',
    ],
    correct: [1],
    explanation: 'A queue decouples producers from consumers, smooths traffic spikes, and lets each side scale independently. It does not inherently reduce latency or guarantee exactly-once.',
    difficulty: 1,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'In Kafka, message ordering is guaranteed…',
    type: 'mcq',
    options: [
      'Globally across all partitions',
      'Within a single partition only',
      'Never — order is random',
      'Only for the first message',
    ],
    correct: [1],
    explanation: 'Kafka orders messages per partition. To get ordering for a key, you route all messages with that key to one partition. Global ordering would need a single partition.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'With at-least-once delivery, a consumer must be…',
    type: 'mcq',
    options: [
      'Idempotent, because a message may be delivered more than once',
      'Stateless',
      'Running a single thread',
      'Storing state in the queue',
    ],
    correct: [0],
    explanation: 'At-least-once may redeliver after a crash, so processing the same message twice must be harmless — the consumer needs idempotency (e.g. a dedup key).',
    difficulty: 2,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'Why is exactly-once delivery hard to achieve in practice?',
    type: 'mcq',
    options: [
      'Networks are too slow',
      'It needs coordination of deduplication and idempotency across producer, broker, and consumer',
      'Queues cannot store messages',
      'Consumers are too fast',
    ],
    correct: [1],
    explanation: 'Exactly-once really means "at-least-once plus dedup plus idempotent consumers," and it requires transactional coordination (like Kafka\'s transactional producer) — not a free guarantee.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'A consumer is slower than the producer. What builds up and what is it called?',
    type: 'scenario',
    options: [
      'Queue lag — the consumer falls behind and messages accumulate',
      'Nothing — queues auto-scale consumers',
      'Data loss — messages are dropped immediately',
      'A deadlock in the queue',
    ],
    correct: [0],
    explanation: 'Consumer lag grows when consumption can\'t keep up. You monitor lag and respond by scaling consumers, adding partitions, or applying backpressure.',
    difficulty: 2,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'Pub/sub differs from point-to-point queues because…',
    type: 'mcq',
    options: [
      'Pub/sub delivers each message to every subscriber',
      'Pub/sub is slower',
      'Point-to-point delivers to every consumer',
      'Pub/sub cannot use Kafka',
    ],
    correct: [0],
    explanation: 'Pub/sub broadcasts a message to all subscribers; point-to-point (or a consumer group) delivers each message to only one competing consumer.',
    difficulty: 1,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'What is a dead-letter queue used for?',
    type: 'mcq',
    options: [
      'Storing the newest messages',
      'Collecting messages that failed processing after retries exhausted',
      'Speeding up consumption',
      'Backing up the entire topic',
    ],
    correct: [1],
    explanation: 'After N failed attempts, a message moves to a dead-letter queue so it can be inspected or replayed manually without blocking the main flow.',
    difficulty: 1,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'Which of the following are real benefits of an async queue? (select all)',
    type: 'multi',
    options: [
      'Decoupling producer and consumer lifecycles',
      'Buffering traffic spikes so consumers stay under load',
      'Peak shaving for downstream services',
      'Making a single request faster',
    ],
    correct: [0, 1, 2],
    explanation: 'Queues decouple, buffer, and smooth spikes. They do not make an individual request faster — a request that now goes through a queue usually takes longer, which you trade for reliability.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'In Kafka, a consumer group lets you…',
    type: 'mcq',
    options: [
      'Broadcast messages to every member',
      'Divide partitions among consumers to process in parallel',
      'Store messages forever',
      'Guarantee global order',
    ],
    correct: [1],
    explanation: 'Consumers in a group split the partitions between them, so each message is processed by exactly one member — parallel processing of a topic.',
    difficulty: 2,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'Adding many more partitions to a Kafka topic…',
    type: 'mcq',
    options: [
      'Always increases throughput with no cost',
      'Increases parallelism but adds rebalance overhead and per-partition costs',
      'Is impossible after creation',
      'Reduces the number of consumers allowed',
    ],
    correct: [1],
    explanation: 'More partitions = more parallelism, but each partition has overhead (files, leaders, rebalance time). Over-partitioning can hurt, not help.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'The transactional outbox pattern is used to…',
    type: 'mcq',
    options: [
      'Write a DB change and its "event to publish" atomically in one transaction',
      'Encrypt messages',
      'Compress messages before sending',
      'Prevent consumers from reading',
    ],
    correct: [0],
    explanation: 'The outbox writes the business change and a pending event in the same DB transaction, then a relay publishes it — avoiding "DB updated but event lost."',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'Backpressure means…',
    type: 'mcq',
    options: [
      'Compressing the messages',
      'Signaling upstream to slow down because a consumer cannot keep up',
      'Restarting the producer',
      'Adding more partitions',
    ],
    correct: [1],
    explanation: 'Backpressure propagates the consumer\'s inability to keep up so producers slow down, preventing unbounded buffering and memory exhaustion.',
    difficulty: 2,
  },
  {
    topicSlug: 'message-queues-and-async',
    prompt: 'What is guaranteed by at-least-once delivery?',
    type: 'mcq',
    options: [
      'Every message is delivered exactly once',
      'Every message is delivered at least once, possibly with duplicates',
      'Messages are delivered in order',
      'No message is ever lost, but none are duplicated',
    ],
    correct: [1],
    explanation: 'At-least-once means no loss but possible duplication — hence the idempotency requirement. It does not guarantee ordering.',
    difficulty: 1,
  },

  // ─── Topic 11: Microservices & API Design ─────────────────────────────
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'A small team should be cautious about jumping straight to microservices because…',
    type: 'scenario',
    options: [
      'Microservices are always slower',
      'You take on distributed-systems complexity: network calls, data ownership, versioning, observability',
      'Microservices require no infra',
      'They prevent team scaling',
    ],
    correct: [1],
    explanation: 'Microservices add a distributed-systems tax (failure handling, data ownership, versioning, tracing). For small teams and systems, a modular monolith often delivers most benefits with far less complexity.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'A modular monolith is…',
    type: 'mcq',
    options: [
      'A monolith deployed many times',
      'One deployable with enforced module boundaries and per-module data ownership',
      'A set of serverless functions',
      'A monolith that cannot scale',
    ],
    correct: [1],
    explanation: 'The modular monolith keeps a single deployable but enforces module boundaries and data ownership, capturing much of microservices discipline without the network complexity.',
    difficulty: 2,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'gRPC is built on which protocol/encoding?',
    type: 'mcq',
    options: ['HTTP/1.1 + JSON', 'HTTP/2 + Protocol Buffers', 'TCP + XML', 'UDP + CSV'],
    correct: [1],
    explanation: 'gRPC uses HTTP/2 (multiplexing, streaming) with binary Protocol Buffers for compact, fast serialization — common for internal service-to-service calls.',
    difficulty: 1,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'What problem does GraphQL most directly solve?',
    type: 'mcq',
    options: [
      'Authentication',
      'Over-fetching / under-fetching — the client asks for exactly the fields it needs',
      'Database sharding',
      'Message ordering',
    ],
    correct: [1],
    explanation: 'GraphQL lets clients request precise shapes, eliminating over-fetching (too much data) and under-fetching (multiple round trips). The cost moves to server-side resolution.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'Your API adds a new optional field. Best practice is to…',
    type: 'scenario',
    options: [
      'Change the response shape and require every client to update',
      'Add the field additively and keep backward compatibility (bump version only for breaking changes)',
      'Launch a whole new service',
      'Remove the old endpoint',
    ],
    correct: [1],
    explanation: 'Additive, non-breaking changes are preferred; version (e.g. /v2/) only when a change breaks existing clients. This keeps old clients working.',
    difficulty: 1,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'A circuit breaker in a microservice system…',
    type: 'mcq',
    options: [
      'Adds more capacity',
      'Fails fast to a default when a downstream service is unhealthy, protecting it from overload',
      'Encrypts service calls',
      'Caches every response',
    ],
    correct: [1],
    explanation: 'When a dependency is failing, the breaker opens and calls fail fast (or return a fallback), giving the dependency time to recover and preventing cascade failures.',
    difficulty: 2,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'Which approaches help with distributed transactions across services? (select all)',
    type: 'multi',
    options: [
      'Saga orchestration (compensating steps)',
      'Transactional outbox + eventual consistency',
      'Pretending the network never fails',
      'Idempotent retries',
    ],
    correct: [0, 1, 3],
    explanation: 'Sagas, outbox + event-driven consistency, and idempotent retries handle multi-service state changes. Ignoring network failures is not a strategy.',
    difficulty: 3,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'In orchestration vs choreography, orchestration means…',
    type: 'mcq',
    options: [
      'Each service reacts to events independently',
      'A central coordinator drives the workflow and calls each step',
      'All services share one database',
      'Services never communicate',
    ],
    correct: [1],
    explanation: 'Orchestration uses a central controller (like a saga coordinator); choreography lets services react to events without a central brain.',
    difficulty: 2,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'Why do services need service discovery?',
    type: 'mcq',
    options: [
      'To find the database',
      'To discover the network addresses of other services, which change as they scale',
      'To discover bugs',
      'To load balance DNS',
    ],
    correct: [1],
    explanation: 'In dynamic environments, instances come and go and IPs change, so a registry (or DNS-based discovery) lets clients find healthy instances.',
    difficulty: 1,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'Why does idempotency matter in payment APIs?',
    type: 'scenario',
    options: [
      'To make requests faster',
      'A retried request with the same idempotency key produces the same result, avoiding double charges',
      'To hide the payment provider',
      'To compress payloads',
    ],
    correct: [1],
    explanation: 'If a network retry re-sends a charge, the idempotency key lets the server recognize the duplicate and return the original result — no double-charge.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'An inter-service call fails transiently. Best retry strategy is…',
    type: 'mcq',
    options: [
      'Retry immediately 100 times',
      'Exponential backoff with jitter, capped retries, then a circuit breaker',
      'Never retry',
      'Reboot the service',
    ],
    correct: [1],
    explanation: 'Immediate retries amplify load on an already struggling service. Backoff + jitter spreads retries; capping and a breaker prevent a retry storm.',
    difficulty: 2,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'A bounded context means…',
    type: 'mcq',
    options: [
      'A service can access any other service\'s database',
      'Each service owns a well-defined slice of the domain and its data',
      'Services must run in one region',
      'A monolith with no boundaries',
    ],
    correct: [1],
    explanation: 'Bounded contexts are the unit of ownership in microservices: clear domain boundaries and private data, shared only through explicit contracts.',
    difficulty: 2,
  },
  {
    topicSlug: 'microservices-and-api-design',
    prompt: 'What is an API gateway NOT typically used for?',
    type: 'mcq',
    options: [
      'Routing requests to the right services',
      'Central auth and rate limiting',
      'Performing heavy business logic',
      'Request aggregation/transformation',
    ],
    correct: [2],
    explanation: 'A gateway handles cross-cutting concerns at the edge (routing, auth, rate limiting, aggregation). Heavy business logic belongs in the services, not the gateway.',
    difficulty: 2,
    isTricky: true,
  },

  // ─── Topic 12: CDN & Edge Computing ───────────────────────────────────
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'A CDN primarily reduces…',
    type: 'mcq',
    options: [
      'Database storage',
      'Latency by serving content from edge nodes near the user, and offloads the origin',
      'API request size',
      'Encryption overhead',
    ],
    correct: [1],
    explanation: 'CDN caches at edge PoPs close to users, cutting latency and origin load. It does not change storage or request sizes.',
    difficulty: 1,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'In a pull (reverse-proxy) CDN, content is cached…',
    type: 'mcq',
    options: [
      'Eagerly pushed to all edges before any request',
      'On demand, the first time an edge receives a request for it',
      'Only in the origin',
      'In the browser only',
    ],
    correct: [1],
    explanation: 'A pull CDN fills its cache when a user requests an object and it is a miss; a push CDN uploads content proactively. Pull is automatic and common.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'The Cache-Control: max-age=3600 header tells the CDN…',
    type: 'mcq',
    options: [
      'To refresh immediately',
      'To serve the cached copy for up to 3600 seconds without rechecking the origin',
      'To cache for exactly one hour in the browser only',
      'To purge all content',
    ],
    correct: [1],
    explanation: 'max-age is how long a cached response is considered fresh. After that, the CDN revalidates or fetches from origin.',
    difficulty: 1,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'A page shows personalized content for each user. Naively CDN-caching it will…',
    type: 'scenario',
    options: [
      'Work perfectly',
      'Serve other users\' personalized data unless you vary by cookie/user or use uncacheable responses',
      'Only cache the HTML',
      'Be automatically secure',
    ],
    correct: [1],
    explanation: 'Personalized content must either be excluded from the cache, keyed with Vary/cookie-aware keys, or served with no-store — otherwise users see each other\'s data.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'After you update an asset, the CDN still serves the old version. Why?',
    type: 'mcq',
    options: [
      'The CDN is broken',
      'The old copy is still within its TTL; invalidation is not instant and must propagate',
      'Browsers block updates',
      'The origin is down',
    ],
    correct: [1],
    explanation: 'Cached objects stay until their TTL expires or you purge them, and even a purge takes time to propagate across PoPs. Invalidation is never immediate.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'A very long TTL on a CDN object causes…',
    type: 'mcq',
    options: [
      'More origin traffic',
      'Stale content served longer',
      'Faster invalidation',
      'Higher bandwidth',
    ],
    correct: [1],
    explanation: 'Long TTL = fewer origin hits but older content. Short TTL = fresher but more origin load. The right TTL balances freshness against origin cost.',
    difficulty: 1,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'The origin is…',
    type: 'mcq',
    options: [
      'A copy of the cache',
      'The authoritative source of content that edges pull from',
      'A load balancer',
      'A DNS server',
    ],
    correct: [1],
    explanation: 'Edges cache copies; the origin holds the source of truth. Edges revalidate/fetch from the origin on misses or expiry.',
    difficulty: 1,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'When a hot object\'s TTL expires at the edge, what can happen?',
    type: 'scenario',
    options: [
      'Nothing special',
      'A cache stampede — many users trigger simultaneous origin requests for the same object',
      'The object is permanently deleted',
      'The edge restarts',
    ],
    correct: [1],
    explanation: 'If many users request a just-expired hot object at once, they all miss and hit the origin together — the thundering herd / stampede. Mitigations: stale-while-revalidate, request coalescing, jittered TTLs.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'Which of the following are good CDN use cases? (select all)',
    type: 'multi',
    options: [
      'Static assets (JS, CSS, images)',
      'Video streaming to a global audience',
      'Per-user encrypted database rows',
      'Globally popular immutable builds',
    ],
    correct: [0, 1, 3],
    explanation: 'CDNs excel at immutable, widely-shared, static content. Per-user private data needs signed URLs, vary headers, or should not be cached at all.',
    difficulty: 2,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'Edge computing means…',
    type: 'mcq',
    options: [
      'Running all logic in one central datacenter',
      'Executing computation at CDN PoPs close to users',
      'Compressing data at the edge of the disk',
      'Using more CPUs on the server',
    ],
    correct: [1],
    explanation: 'Edge computing moves small computations (auth, routing, rewriting, custom logic) to the network edge, reducing round trips to the origin.',
    difficulty: 2,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'Your API returns per-user JSON. The correct approach is…',
    type: 'scenario',
    options: [
      'Cache it globally with a long TTL',
      'Do not cache it, or use vary/signed URLs/cookie-aware caching if appropriate',
      'Cache only on the origin',
      'Serve it from a static file',
    ],
    correct: [1],
    explanation: 'Per-user data is not cacheable globally. Either bypass the cache or key responses correctly so users never receive another user\'s data.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'DNS-based geo-routing to the "nearest" region does NOT guarantee…',
    type: 'mcq',
    options: [
      'That the user\'s data is there',
      'The lowest latency (nearest ≠ fastest, especially across congested or cost-optimized paths)',
      'A faster TLS handshake',
      'Load balance',
    ],
    correct: [1],
    explanation: 'Geo-DNS picks the closest region by geography, but path congestion, peering, and CDN health can make a different region faster. Also the user\'s data may live elsewhere.',
    difficulty: 3,
    isTricky: true,
  },
  {
    topicSlug: 'cdn-and-edge',
    prompt: 'Signed CDN URLs are used to…',
    type: 'mcq',
    options: [
      'Make URLs shorter',
      'Grant time-limited access to private content',
      'Encrypt the payload',
      'Speed up DNS',
    ],
    correct: [1],
    explanation: 'A signed URL carries an expiry + signature, letting you serve private content through the CDN while controlling who can access it and for how long.',
    difficulty: 2,
  },

  // ─── Topic 13: Observability & Reliability ────────────────────────────
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'The three pillars of observability are…',
    type: 'mcq',
    options: [
      'Logs, metrics, and traces',
      'CPU, memory, and disk',
      'Alerting, paging, and dashboards',
      'Build, deploy, and release',
    ],
    correct: [0],
    explanation: 'Observability = logs (events), metrics (aggregated numbers), traces (request flows). Dashboards and alerting consume these pillars.',
    difficulty: 1,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'An availability target of 99.9% means roughly how much downtime per year?',
    type: 'scenario',
    options: ['52 minutes', '8.76 hours', '1 hour', '1 day'],
    correct: [1],
    explanation: '99.9% = 0.1% downtime = ~8.76 hours/year. (99.99% is ~52.6 min/year — easy to mix up.)',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'RPO vs RTO: which is which?',
    type: 'mcq',
    options: [
      'RPO = recovery point (acceptable data loss); RTO = recovery time (acceptable downtime)',
      'RPO = downtime; RTO = data loss',
      'Both measure uptime',
      'RPO is about security',
    ],
    correct: [0],
    explanation: 'RPO bounds how much data you can afford to lose (last backup/sync point); RTO bounds how quickly you must be back up. They trade against cost differently.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'An error budget is…',
    type: 'mcq',
    options: [
      'A fund for buying servers',
      'The allowed amount of failure implied by an SLO, which you can spend on deployments',
      'A list of known bugs',
      'A budget for testing',
    ],
    correct: [1],
    explanation: 'Error budget = 100% − SLO. If you have 99.9% availability, you may spend 0.1% on risky deploys — embracing that failure is allowed, not panic.',
    difficulty: 2,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'p99 latency is 2 s but average latency is 100 ms. What does this tell you?',
    type: 'scenario',
    options: [
      'The system is fine',
      'A small fraction of requests are very slow (tail latency), which matters for user experience',
      'The p99 is wrong',
      'The average should be ignored',
    ],
    correct: [1],
    explanation: 'High p99 with low average means a tail of slow requests. For any user that hits the tail, experience is bad — tail latency drives SLOs.',
    difficulty: 2,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Distributed tracing helps you…',
    type: 'mcq',
    options: [
      'Encrypt cross-service calls',
      'Follow a single request across many services using trace/span IDs',
      'Scale the database',
      'Reduce log size',
    ],
    correct: [1],
    explanation: 'A trace ID is propagated across services; spans record each hop. This lets you see where time goes in a request path.',
    difficulty: 1,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'The best alert is one that…',
    type: 'mcq',
    options: [
      'Fires on every warning log line',
      'Fires on a user-facing symptom (SLO breach) and is actionable',
      'Fires only at night',
      'Never fires',
    ],
    correct: [1],
    explanation: 'Alert on symptoms that affect users (e.g. error rate over budget), not on every noisy log. Noise causes alert fatigue and real incidents get missed.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Which of the following are common metric types? (select all)',
    type: 'multi',
    options: ['Counter', 'Gauge', 'Histogram', 'Compiler'],
    correct: [0, 1, 2],
    explanation: 'Counters (monotonic counts), gauges (current values like CPU), histograms (distributions like latency). "Compiler" is not a metric type.',
    difficulty: 1,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Active-passive (failover) high availability means…',
    type: 'mcq',
    options: [
      'Both nodes serve traffic',
      'A standby node sits idle and takes over on failure — wasting half the capacity',
      'The system runs on active only',
      'Nodes sync in real time',
    ],
    correct: [1],
    explanation: 'Active-passive keeps a warm standby; it is simpler but under-utilizes capacity. Active-active serves traffic on all nodes but is harder to build.',
    difficulty: 2,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Why are structured logs better than free-form text logs?',
    type: 'mcq',
    options: [
      'They are smaller',
      'They are machine-parseable and queryable (key/value fields), enabling aggregation and alerts',
      'They never fail',
      'They are encrypted',
    ],
    correct: [1],
    explanation: 'Structured logs (JSON/key=value) can be filtered, aggregated, and alerted on at scale. Free-form text is hard to query reliably.',
    difficulty: 1,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Chaos engineering means…',
    type: 'mcq',
    options: [
      'Deploying untested code',
      'Deliberately injecting failures (kill nodes, delay packets) to validate resilience',
      'Restarting all services',
      'Ignoring incident reports',
    ],
    correct: [1],
    explanation: 'Chaos experiments test that your system survives real failure modes — controlled, in production-ish environments, with a hypothesis about steady-state behavior.',
    difficulty: 2,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: '99.99% availability per year leaves how much allowed downtime?',
    type: 'scenario',
    options: ['~52.6 minutes', '~8.76 hours', '~1 hour', '~5 minutes'],
    correct: [0],
    explanation: '99.99% = 0.01% downtime = ~52.6 minutes/year. Compare: 99.9% = 8.76 hours. Each extra nine is ~10× harder to hold.',
    difficulty: 2,
    isTricky: true,
  },
  {
    topicSlug: 'observability-and-reliability',
    prompt: 'Why is a 100% uptime SLO generally a bad idea?',
    type: 'mcq',
    options: [
      'It is easy to meet',
      'It leaves zero error budget, forces impossible rigor, and costs explode; better to target a realistic SLO and budget for failures',
      'It is against policy',
      'It makes monitoring redundant',
    ],
    correct: [1],
    explanation: '100% gives no room for deploys or incidents and demands unbounded redundancy. Real systems embrace a target (e.g. 99.99%) and use the error budget.',
    difficulty: 2,
    isTricky: true,
  },
]
